#### 1. Implement all activation function.

In [6]:
import numpy as np

def sigmoid(X):
    return 1 / (1 + np.exp(-X))

def tanh(X):
    return (np.exp(X)-np.exp(-X)/np.exp(X)+np.exp(-X))

def relu(X):
    return np.maximum(0, X)

def step_function(X):
    return np.where(X > 0, 1, 0)

def softmax(X): 
    exp_x = np.exp(X - np.max(X))
    return exp_x / np.sum(exp_x)

X = np.array([0.5, 0.2, 0.1]) # 3 input neuron
W1 = np.array([[0.1, 0.2, 0.3], # 1st layer weight
               [0.4, 0.5, 0.6],
               [0.7, 0.8, 0.9]])
b1 = np.array([0.1, 0.1, 0.1]) # Bias for 1st layer
W2 = np.array([[0.1, 0.4], # 2nd layer weight
               [0.2, 0.5],
               [0.3, 0.6]])
b2 = np.array([0.2, 0.2]) # Bias for 2nd layer

Z1 = np.dot(X, W1) + b1
A1 = {
    "Sigmoid": sigmoid(Z1),
    "Tanh": tanh(Z1),
    "ReLU": relu(Z1),
    "Step Function": step_function(Z1)
}

Z2 = np.dot(A1["Sigmoid"], W2) + b2
A2 = softmax(Z2)

for name, y in A1.items():
    print(f"{name} Activation:")
    print(y)
    print()

print("Softmax Output:")
print(A2)

Sigmoid Activation:
[0.57444252 0.5938731  0.61301418]

Tanh Activation:
[1.54186539 1.67847957 1.81683859]

ReLU Activation:
[0.3  0.38 0.46]

Step Function Activation:
[1 1 1]

Softmax Output:
[0.36949149 0.63050851]


#### Q) Implement a two-layer perceptron with sigmoid activation in the hidden layer and softmax in the output layer. Use it for a simple classification task.

In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

# Layer 1
X = np.array([0.5, 0.2, 0.1])
W1 = np.array([[0.1, 0.2, 0.3], 
               [0.4, 0.5, 0.6], 
               [0.7, 0.8, 0.9]])
b1 = np.array([0.2, 0.2, 0.2])

#  Output Layer 2
W2 = np.array([[0.1, 0.4], 
               [0.2, 0.5], 
               [0.3, 0.6]])
b2 = np.array([0.3, 0.3])

Z1 = np.dot(X, W1) + b1
print("Summation at Hidden Layer (Z1):",Z1)
A1 = sigmoid(Z1)
print("Output of Hidden Layer (A1):",A1)

Z2 = np.dot(A1, W2) + b2
print("Summation at Output Layer (Z2):",Z2)
A2 = softmax(Z2)
print("Final Output (A2):",A2)

Summation at Hidden Layer (Z1): [0.4  0.48 0.56]
Output of Hidden Layer (A1): [0.59868766 0.61774787 0.63645254]
Summation at Output Layer (Z2): [0.6743541  1.23022053]
Final Output (A2): [0.36450443 0.63549557]
